# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Autotagger
      id: autotagger
      uses: butlerlogic/action-autotag@stable
      with:
        strategy: regex
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        root: "setup.cfg"
        regex_pattern: "version = (.*)$"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      if: steps.id.outputs.tagcreated == 'yes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.id.outputs.tagname }}
        release_name: Release ${{ steps.id.outputs.tagname }}
        body: |
          ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false 
    - name: Set up Python
      uses: actions/setup-python@v2
      if: steps.id.outputs.tagcreated == 'yes'
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        # temp not do stuff while testing
        #twine upload dist/*
